[package]
name = "aoc-13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
ansi_term = "0.12.1"
once_cell = "1.16.0"